In [1]:
import pandas as pd
import os

#### IMPORTING FILES

In [2]:
fund_master=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\01_fund_master.csv")
nav_history=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\02_nav_history.csv")
aum_by_fund_house=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\03_aum_by_fund_house.csv")
monthly_sip_inflows=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\04_monthly_sip_inflows.csv")
category_inflows=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\05_category_inflows.csv")
industry_folio_count=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\06_industry_folio_count.csv")
scheme_peformance=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\07_scheme_performance.csv")
investors_transcations=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\08_investor_transactions.csv")
portfolio_holdings=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\09_portfolio_holdings.csv")
benchmark_indices=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\Mutual-Fund-Analysis\data\raw\10_benchmark_indices.csv")

In [3]:
fund_master.shape

(40, 15)

In [4]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [5]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [6]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [7]:
nav_history.shape

(46000, 3)

In [8]:
nav_history.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [9]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [10]:
aum_by_fund_house.shape

(90, 5)

In [11]:
aum_by_fund_house.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [12]:
aum_by_fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [13]:
monthly_sip_inflows.shape

(48, 6)

In [14]:
monthly_sip_inflows.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [15]:
monthly_sip_inflows.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [16]:
monthly_sip_inflows.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [17]:
category_inflows.shape

(144, 3)

In [18]:
category_inflows.dtypes

month                   str
category                str
net_inflow_crore    float64
dtype: object

In [19]:
category_inflows.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [20]:
industry_folio_count.shape

(21, 6)

In [21]:
industry_folio_count.dtypes

month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [22]:
industry_folio_count.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [23]:
scheme_peformance.shape

(40, 19)

In [24]:
scheme_peformance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [25]:
scheme_peformance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [26]:
investors_transcations.shape

(32778, 13)

In [27]:
investors_transcations.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [28]:
investors_transcations.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [29]:
portfolio_holdings.shape

(322, 8)

In [30]:
portfolio_holdings.dtypes

amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

In [31]:
portfolio_holdings.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [32]:
benchmark_indices.shape

(8050, 3)

In [33]:
benchmark_indices.dtypes

date               str
index_name         str
close_value    float64
dtype: object

In [34]:
benchmark_indices.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

##### EXPLORING FUND MASTER

In [35]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [36]:
fund_master['fund_house'].unique()

<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [37]:
fund_master['category'].unique()

<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [38]:
fund_master['sub_category'].unique()

<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [39]:
fund_master['risk_category'].unique()

<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [40]:
fund_master["amfi_code"].nunique()

40

##### Validate AMFI Code

In [41]:
nav_history.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

##### Confirm every code in fund_master exists in nav_history

In [42]:
fund_master_codes = set(fund_master["amfi_code"])
nav_history_codes = set(nav_history["amfi_code"])

missing_codes = fund_master_codes - nav_history_codes
missing_codes

set()

##### FETCHING DATA SCHEMES DATA

In [44]:
import requests

In [47]:
response = requests.get("https://api.mfapi.in/mf/119018")
data = response.json()

hdfc_nav = pd.DataFrame(data["data"])
hdfc_nav["scheme_code"] = 119018
hdfc_nav["fund_name"] = data["meta"]["scheme_name"]

In [48]:
hdfc_nav.head()

,date,nav,scheme_code,fund_name
0,27-07-2026,1229.57400,119018,HDFC Large Cap Fund - Growth Option - Direct Plan
1,24-07-2026,1215.97600,119018,HDFC Large Cap Fund - Growth Option - Direct Plan
2,23-07-2026,1220.84900,119018,HDFC Large Cap Fund - Growth Option - Direct Plan
3,22-07-2026,1226.74300,119018,HDFC Large Cap Fund - Growth Option - Direct Plan
4,21-07-2026,1238.22300,119018,HDFC Large Cap Fund - Growth Option - Direct Plan

In [49]:
response = requests.get("https://api.mfapi.in/mf/119598", timeout=10)
data = response.json()

sbi_nav = pd.DataFrame(data["data"])
sbi_nav["scheme_code"] = 119598
sbi_nav["fund_name"] = data["meta"]["scheme_name"]

sbi_nav.head()

         date        nav  scheme_code                               fund_name
0  27-07-2026  103.91770       119598  SBI Large Cap FUND-DIRECT PLAN -GROWTH
1  24-07-2026  102.95350       119598  SBI Large Cap FUND-DIRECT PLAN -GROWTH
2  23-07-2026  103.19130       119598  SBI Large Cap FUND-DIRECT PLAN -GROWTH
3  22-07-2026  103.65920       119598  SBI Large Cap FUND-DIRECT PLAN -GROWTH
4  21-07-2026  104.78010       119598  SBI Large Cap FUND-DIRECT PLAN -GROWTH

In [51]:
response = requests.get("https://api.mfapi.in/mf/118632", timeout=10)
data = response.json()

nippon_nav = pd.DataFrame(data["data"])
nippon_nav["scheme_code"] = 118632
nippon_nav["fund_name"] = data["meta"]["scheme_name"]

nippon_nav.head()

,date,nav,scheme_code,fund_name
0,27-07-2026,100.44980,118632,Nippon India Large Cap Fund - Direct Plan Grow...
1,24-07-2026,99.32730,118632,Nippon India Large Cap Fund - Direct Plan Grow...
2,23-07-2026,99.72940,118632,Nippon India Large Cap Fund - Direct Plan Grow...
3,22-07-2026,100.09970,118632,Nippon India Large Cap Fund - Direct Plan Grow...
4,21-07-2026,101.06690,118632,Nippon India Large Cap Fund - Direct Plan Grow...

In [52]:
response = requests.get("https://api.mfapi.in/mf/120465", timeout=10)
data = response.json()

axis_nav = pd.DataFrame(data["data"])
axis_nav["scheme_code"] = 120465
axis_nav["fund_name"] = data["meta"]["scheme_name"]

axis_nav.head()

,date,nav,scheme_code,fund_name
0,27-07-2026,69.20000,120465,Axis Large Cap Fund - Direct Plan - Growth
1,24-07-2026,68.29000,120465,Axis Large Cap Fund - Direct Plan - Growth
2,23-07-2026,68.64000,120465,Axis Large Cap Fund - Direct Plan - Growth
3,22-07-2026,68.99000,120465,Axis Large Cap Fund - Direct Plan - Growth
4,21-07-2026,69.56000,120465,Axis Large Cap Fund - Direct Plan - Growth

In [54]:
response = requests.get("https://api.mfapi.in/mf/120152", timeout=30)
data = response.json()

kotak_nav = pd.DataFrame(data["data"])
kotak_nav["scheme_code"] = 120152
kotak_nav["fund_name"] = data["meta"]["scheme_name"]

kotak_nav.head()

         date        nav  scheme_code                                fund_name
0  27-07-2026  656.10100       120152  Kotak Large Cap  Fund - Growth - Direct
1  24-07-2026  649.24300       120152  Kotak Large Cap  Fund - Growth - Direct
2  23-07-2026  651.58500       120152  Kotak Large Cap  Fund - Growth - Direct
3  22-07-2026  655.83100       120152  Kotak Large Cap  Fund - Growth - Direct
4  21-07-2026  661.61800       120152  Kotak Large Cap  Fund - Growth - Direct

In [55]:
response = requests.get("https://api.mfapi.in/mf/120586", timeout=30)
data = response.json()

icici_nav = pd.DataFrame(data["data"])
icici_nav["scheme_code"] = 120586
icici_nav["fund_name"] = data["meta"]["scheme_name"]

icici_nav.head()

,date,nav,scheme_code,fund_name
0,27-07-2026,119.44000,120586,ICICI Prudential Large Cap Fund (erstwhile Blu...
1,24-07-2026,118.38000,120586,ICICI Prudential Large Cap Fund (erstwhile Blu...
2,23-07-2026,118.67000,120586,ICICI Prudential Large Cap Fund (erstwhile Blu...
3,22-07-2026,119.04000,120586,ICICI Prudential Large Cap Fund (erstwhile Blu...
4,21-07-2026,120.09000,120586,ICICI Prudential Large Cap Fund (erstwhile Blu...

In [56]:
hdfc_nav.to_csv("../data/raw/live_nav_hdfc_large_cap.csv", index=False)

In [57]:
sbi_nav.to_csv("../data/raw/live_nav_sbi_large_cap.csv", index=False)

In [58]:
icici_nav.to_csv("../data/raw/live_nav_icici_large_cap.csv", index=False)

In [59]:
nippon_nav.to_csv("../data/raw/live_nav_nippon_large_cap.csv", index=False)

In [60]:
axis_nav.to_csv("../data/raw/live_nav_axis_large_cap.csv", index=False)

In [61]:
kotak_nav.to_csv("../data/raw/live_nav_kotak_large_cap.csv", index=False)